import { z } from "zod";
const cents = z.coerce.number().int().min(0).max(100_000_000);
const optionalCents = z.preprocess((value) => value === "" || value === undefined ? undefined : value, cents.optional());
const slug = z.string().trim().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/).max(160);
// Drafts may be saved incomplete: an empty slug is derived from the name on the
// server. A non-empty slug still has to be well formed. Publication readiness —
// not this schema — is what gates a product going live.
const optionalSlug = z.string().trim().max(160).refine((value) => value === "" || /^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(value), "Use lowercase letters, numbers and hyphens").optional().default("");

export const adminProductSchema = z.object({
  internalName: z.string().trim().min(2).max(160), nameDe: z.string().trim().max(160).optional().default(""), slugDe: optionalSlug,
  nameEn: z.string().trim().max(160).optional().default(""), slugEn: optionalSlug,
  shortDescriptionDe: z.string().trim().max(500).optional().default(""), descriptionDe: z.string().trim().max(20_000).optional().default(""),
  shortDescriptionEn: z.string().trim().max(500).optional().default(""), descriptionEn: z.string().trim().max(20_000).optional().default(""),
  ingredientsDe: z.string().trim().max(4_000).optional().default(""), ingredientsEn: z.string().trim().max(4_000).optional().default(""),
  allergenDe: z.string().trim().max(4_000).optional().default(""), allergenEn: z.string().trim().max(4_000).optional().default(""),
  storageDe: z.string().trim().max(4_000).optional().default(""), storageEn: z.string().trim().max(4_000).optional().default(""),
  categoryId: z.string().trim().optional().default(""), countryOfOrigin: z.string().trim().max(100).optional().default(""), regionOfOrigin: z.string().trim().max(100).optional().default(""), responsibleFoodBusiness: z.string().trim().max(500).optional().default(""),
  seoTitleDe: z.string().trim().max(70).optional().default(""), seoTitleEn: z.string().trim().max(70).optional().default(""), metaDescriptionDe: z.string().trim().max(180).optional().default(""), metaDescriptionEn: z.string().trim().max(180).optional().default(""),
  featured: z.coerce.boolean().default(false), bestseller: z.coerce.boolean().default(false), newProduct: z.coerce.boolean().default(false), giftSuitable: z.coerce.boolean().default(false)
});

export const adminVariantSchema = z.object({ productId: z.string().min(1), sku: z.string().trim().min(3).max(80).transform((value) => value.toUpperCase()), weightGrams: z.coerce.number().int().positive().max(100_000), shippingWeightG: z.coerce.number().int().positive().max(100_000), priceCents: cents, compareAtCents: optionalCents, costCents: optionalCents, vatRateBps: z.coerce.number().int().min(0).max(10_000), barcode: z.string().trim().max(40).optional().default(""), active: z.coerce.boolean().default(true), sortOrder: z.coerce.number().int().min(0).max(10_000), initialStock: z.coerce.number().int().min(0).max(1_000_000), lowStockThreshold: z.coerce.number().int().min(0).max(1_000_000) });
export const inventoryAdjustmentSchema = z.object({ inventoryId: z.string().min(1), quantity: z.coerce.number().int().refine((value) => value !== 0, "Quantity cannot be zero"), reason: z.enum(["Supplier delivery", "Manual correction", "Damaged stock", "Expired stock", "Returned stock", "Order adjustment", "Stock count correction"]), internalNote: z.string().trim().max(1_000).optional().default("") });
export const categorySchema = z.object({ nameDe: z.string().trim().min(2).max(120), nameEn: z.string().trim().min(2).max(120), slugDe: slug, slugEn: slug, descriptionDe: z.string().trim().max(4_000), descriptionEn: z.string().trim().max(4_000), seoTitleDe: z.string().trim().max(70), seoTitleEn: z.string().trim().max(70), metaDescriptionDe: z.string().trim().max(180), metaDescriptionEn: z.string().trim().max(180), parentId: z.string().optional().default("") });
export const couponAdminSchema = z.object({ code: z.string().trim().min(3).max(32).transform((value) => value.toUpperCase()), type: z.enum(["PERCENTAGE", "FIXED", "FREE_SHIPPING"]), value: cents, startsAt: z.string().optional(), expiresAt: z.string().optional(), minimumOrderCents: optionalCents, usageLimit: z.preprocess((value) => value === "" ? undefined : value, z.coerce.number().int().positive().optional()), perCustomerLimit: z.preprocess((value) => value === "" ? undefined : value, z.coerce.number().int().positive().optional()), active: z.coerce.boolean().default(false) }).refine((data) => data.type !== "PERCENTAGE" || data.value <= 10_000, { path: ["value"], message: "Percentage cannot exceed 100%" });
export const giftBoxAdminSchema = z.object({ nameDe: z.string().trim().min(2).max(160), nameEn: z.string().trim().min(2).max(160), slugDe: slug, slugEn: slug, descriptionDe: z.string().trim().min(10).max(5_000), descriptionEn: z.string().trim().min(10).max(5_000), sizeName: z.enum(["SMALL", "MEDIUM", "LARGE"]), basePriceCents: cents, capacityUnits: z.coerce.number().int().positive(), minItems: z.coerce.number().int().positive(), maxItems: z.coerce.number().int().positive(), fixed: z.coerce.boolean().default(false), active: z.coerce.boolean().default(false), seoTitleDe: z.string().trim().max(70), seoTitleEn: z.string().trim().max(70), metaDescriptionDe: z.string().trim().max(180), metaDescriptionEn: z.string().trim().max(180) }).refine((data) => data.minItems <= data.maxItems && data.maxItems <= data.capacityUnits, { message: "Selection limits must fit box capacity", path: ["maxItems"] });
export const wholesaleDecisionSchema = z.object({ applicationId: z.string().min(1), status: z.enum(["UNDER_REVIEW", "MORE_INFORMATION_REQUIRED", "APPROVED", "REJECTED"]), internalNotes: z.string().trim().max(4_000).optional().default(""), minimumOrderCents: optionalCents, invoicePaymentEligible: z.coerce.boolean().default(false) });
